### ISSUE TITLE
.htaccess im Ordner html fehlt

### ISSUE THREAD

**Issue by katgirl** [dominikzogg-legacy/ContaoDirectentries#2]
Es kann die Datei directentries.css nicht geladen werden, da das Verzeichnis in C3 geschützt ist, hier muss es wieder freigegeben werden.

**Comment by dominikzogg** [comment]
Hallo Kirsten

Kannst du nochmals kurz testen (hab das voll vergessen, da ich kein Apache nutze)?

Gruss Dominik

**Comment by katgirl** [comment]
Danke klappt super ;-)

**Comment by dominikzogg** [comment]
np, danke fürs ticket
